apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.discord.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.discord.vault }}/items/{{ .Values.discord.item }}"
