apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onepassword.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.onepassword.vault }}/items/{{ .Values.onepassword.item }}"
